# Generated by Django 4.0.3 on 2022-10-29 06:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0007_remove_symptoms_created'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='created',
            field=models.DateTimeField(auto_now_add=True, default=None),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='symptoms',
            name='updated',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
