# Generated by Django 4.0.3 on 2022-10-29 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0008_symptoms_created_symptoms_updated'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='username',
            field=models.CharField(default=None, max_length=255),
            preserve_default=False,
        ),
    ]
