# Generated by Django 4.0.3 on 2022-10-29 07:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('dementia', '0011_alter_symptoms_username'),
    ]

    operations = [
        migrations.AlterField(
            model_name='symptoms',
            name='username',
            field=models.ManyToManyField(related_name='symptoms', to=settings.AUTH_USER_MODEL),
        ),
        migrations.CreateModel(
            name='quetions',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(max_length=200)),
                ('answer', models.TextField(max_length=300)),
                ('active', models.BooleanField(default=True)),
                ('created', models.DateTimeField(auto_now_add=True)),
                ('updated', models.DateTimeField(auto_now=True)),
                ('username', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='questions', to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
