# Generated by Django 4.0.3 on 2022-10-29 11:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('dementia', '0015_alter_questions_answer'),
    ]

    operations = [
        migrations.AddField(
            model_name='symptoms',
            name='guidlinevideo',
            field=models.URLField(default=None),
            preserve_default=False,
        ),
    ]
